/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/automations/': RouteRecordInfo<
      '/automations/',
      '/automations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/automations/[id]': RouteRecordInfo<
      '/automations/[id]',
      '/automations/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/card/[cardId]': RouteRecordInfo<
      '/card/[cardId]',
      '/card/:cardId',
      { cardId: ParamValue<true> },
      { cardId: ParamValue<false> },
      | never
    >,
    '/crm/[slug]': RouteRecordInfo<
      '/crm/[slug]',
      '/crm/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/crm/tasks': RouteRecordInfo<
      '/crm/tasks',
      '/crm/tasks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inbox': RouteRecordInfo<
      '/inbox',
      '/inbox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/invite/[inviteCode]': RouteRecordInfo<
      '/invite/[inviteCode]',
      '/invite/:inviteCode',
      { inviteCode: ParamValue<true> },
      { inviteCode: ParamValue<false> },
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pm/list/[listId]/': RouteRecordInfo<
      '/pm/list/[listId]/',
      '/pm/list/:listId',
      { listId: ParamValue<true> },
      { listId: ParamValue<false> },
      | never
    >,
    '/register': RouteRecordInfo<
      '/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/[section]': RouteRecordInfo<
      '/settings/[section]',
      '/settings/:section',
      { section: ParamValue<true> },
      { section: ParamValue<false> },
      | never
    >,
    '/settings/card-types/[id]': RouteRecordInfo<
      '/settings/card-types/[id]',
      '/settings/card-types/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/settings/notifications/[channel]': RouteRecordInfo<
      '/settings/notifications/[channel]',
      '/settings/notifications/:channel',
      { channel: ParamValue<true> },
      { channel: ParamValue<false> },
      | never
    >,
    '/whiteboard': RouteRecordInfo<
      '/whiteboard',
      '/whiteboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/automations/index.vue': {
      routes:
        | '/automations/'
      views:
        | never
    }
    'src/pages/automations/[id].vue': {
      routes:
        | '/automations/[id]'
      views:
        | never
    }
    'src/pages/card/[cardId].vue': {
      routes:
        | '/card/[cardId]'
      views:
        | never
    }
    'src/pages/crm/[slug].vue': {
      routes:
        | '/crm/[slug]'
      views:
        | never
    }
    'src/pages/crm/tasks.vue': {
      routes:
        | '/crm/tasks'
      views:
        | never
    }
    'src/pages/inbox.vue': {
      routes:
        | '/inbox'
      views:
        | never
    }
    'src/pages/invite/[inviteCode].vue': {
      routes:
        | '/invite/[inviteCode]'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/pm/list/[listId]/index.vue': {
      routes:
        | '/pm/list/[listId]/'
      views:
        | never
    }
    'src/pages/register.vue': {
      routes:
        | '/register'
      views:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
    }
    'src/pages/settings/[section].vue': {
      routes:
        | '/settings/[section]'
      views:
        | never
    }
    'src/pages/settings/card-types/[id].vue': {
      routes:
        | '/settings/card-types/[id]'
      views:
        | never
    }
    'src/pages/settings/notifications/[channel].vue': {
      routes:
        | '/settings/notifications/[channel]'
      views:
        | never
    }
    'src/pages/whiteboard.vue': {
      routes:
        | '/whiteboard'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
